/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.HashMap;
import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;
import static spark.Spark.*;
import java.util.Map;

import javax.xml.ws.Response;

import java.util.ArrayList;
public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");
        String layout = "templates/layout.vtl";
        
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "template/index.vtl");
            return new ModelAndView(model, layout);
        },new VelocityTemplateEngine());
    }
}
