/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.HashMap;
import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;
import static spark.Spark.*;
import java.util.Map;

import javax.xml.ws.Response;

import java.util.ArrayList;
public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");
        String layout = "templates/layout.vtl";
        
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("heros", request.session().attribute("heros"));
            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        },new VelocityTemplateEngine());

        post("/heros", (request, response) ->{
            Map<String, Object> model = new HashMap<String, Object>();

            ArrayList<Heros> heros = request.session().attribute("heros");
            if (heros==null) {
                heros = new ArrayList<Heros>();
                request.session().attribute("heros",heros);
            }
            String name = request.queryParams("SuperHero-Name");
            int age = Integer.parseInt(request.queryParams("hero-age"));
            String power = request.queryParams("special-power");
            String weakness = request.queryParams("weakness");
            Heros myHeros = new Heros(name,age,power,weakness);
            
            heros.add(myHeros);
            model.put("template", "templates/success.vtl");
            return new ModelAndView(model, layout);
        },new VelocityTemplateEngine());




    }
}
